### ISSUE TITLE
Missing Batch Info during Returnn Network construction via NNetConstructor 

### ISSUE THREAD

**Issue by Atticus1806** [rwth-i6/i6_experiments#73]
I am not 100% sure where to post this Issue, but since it happens during construction via `ReturnnCommonSerializer` and the code is here I will post it here. 
Constructing a returnn_common config with said serializer causes Returnn to crash early during construction:
```
EXCEPTION
Traceback (most recent call last):
  File "/u/hilmes/experiments/tts_new_sis/work/i6_core/tools/git/CloneGitRepositoryJob.ClTwHzgXqVmV/output/repository/rnn.py", line 11, in <module>
    line: main()
    locals:
      main = <local> <function main at 0x7ff41540ef70>
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.ClTwHzgXqVmV/output/repository/returnn/__main__.py", line 657, in main
    line: execute_main_task()
    locals:
      execute_main_task = <global> <function execute_main_task at 0x7ff41540ee50>
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.ClTwHzgXqVmV/output/repository/returnn/__main__.py", line 455, in execute_main_task
    line: engine.init_train_from_config(config, train_data, dev_data, eval_data)
    locals:
      engine = <global> <returnn.tf.engine.Engine object at 0x7ff32f837520>
      engine.init_train_from_config = <global> <bound method Engine.init_train_from_config of <returnn.tf.engine.Engine object at 0x7ff32f837520>>
      config = <global> <returnn.config.Config object at 0x7ff42aaf8d00>
      train_data = <global> <MetaDataset 'train' epoch=1>
      dev_data = <global> <MetaDataset 'dev' epoch=1>
      eval_data = <global> None
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.ClTwHzgXqVmV/output/repository/returnn/tf/engine.py", line 1056, in Engine.init_train_from_config
    line: self.init_network_from_config(config)
    locals:
      self = <local> <returnn.tf.engine.Engine object at 0x7ff32f837520>
      self.init_network_from_config = <local> <bound method Engine.init_network_from_config of <returnn.tf.engine.Engine object at 0x7ff32f837520>>
      config = <local> <returnn.config.Config object at 0x7ff42aaf8d00>
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.ClTwHzgXqVmV/output/repository/returnn/tf/engine.py", line 1121, in Engine.init_network_from_config
    line: self._init_network(net_desc=net_dict, epoch=self.epoch)
    locals:
      self = <local> <returnn.tf.engine.Engine object at 0x7ff32f837520>
      self._init_network = <local> <bound method Engine._init_network of <returnn.tf.engine.Engine object at 0x7ff32f837520>>
      net_desc = <not found>
      net_dict = <local> {'ctc_aligner_ctc_loss': {'class': 'copy', 'from': 'ctc_loss', 'loss': 'as_is', 'out_shape': {Dim{B}}}, 'ctc_aligner_mean_squared_difference_reduce': {'class': 'copy', 'from': 'mean_squared_difference', 'loss': 'as_is', 'loss_opts': {'scale': 0.5}, 'out_shape': {Dim{'audio_features_time'[B?]}, Di..., len = 19
      epoch = <local> None
      self.epoch = <local> 1
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.ClTwHzgXqVmV/output/repository/returnn/tf/engine.py", line 1295, in Engine._init_network
    line: extern_data.init_from_config(config=self.config, auto_create_placeholders=not use_dataset_pipeline)
    locals:
      extern_data = <local> <ExternData data={}>
      extern_data.init_from_config = <local> <bound method ExternData.init_from_config of <ExternData data={}>>
      config = <not found>
      self = <local> <returnn.tf.engine.Engine object at 0x7ff32f837520>
      self.config = <local> <returnn.config.Config object at 0x7ff42aaf8d00>
      auto_create_placeholders = <not found>
      use_dataset_pipeline = <local> False
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.ClTwHzgXqVmV/output/repository/returnn/tf/network.py", line 68, in ExternData.init_from_config
    line: self.data[key] = Data(name=key, auto_create_placeholders=auto_create_placeholders, **init_args)
    locals:
      self = <local> <ExternData data={}>
      self.data = <local> {}
      key = <local> 'audio_features', len = 14
      Data = <global> <class 'returnn.tf.util.data.Data'>
      name = <not found>
      auto_create_placeholders = <local> True
      init_args = <local> {'dim_tags': (Dim{B}, Dim{'audio_features_time'[B?]}, Dim{F'audio_features_feature'(80)}), 'dtype': 'float32', 'time_dim_axis': 1, 'available_for_inference': False}
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.ClTwHzgXqVmV/output/repository/returnn/tf/util/data.py", line 2778, in Data.__init__
    line: self.sanity_check(assume_complete=False)
    locals:
      self = <local> Data{'audio_features', [B?,T|'audio_features_time'[B?],F|F'audio_features_feature'(80)], available_for_inference=False}
      self.sanity_check = <local> <bound method Data.sanity_check of Data{'audio_features', [B?,T|'audio_features_time'[B?],F|F'audio_features_feature'(80)], available_for_inference=False}>
      assume_complete = <not found>
  File "/work/asr3/rossenbach/hilmes/sisyphus_experiments/new_tts/i6_core/tools/git/CloneGitRepositoryJob.ClTwHzgXqVmV/output/repository/returnn/tf/util/data.py", line 2876, in Data.sanity_check
    line: assert tag.batch == tag.dyn_size_ext.batch
    locals:
      tag = <local> Dim{'audio_features_time'[B?]}
      tag.batch = <local> BatchInfo{B(-1)}
      tag.dyn_size_ext = <local> Data{'audio_features_dim0_size', [B?], dtype='int32'}
      tag.dyn_size_ext.batch = <local> None
AssertionError

```

The generated returnn config (leaving out the generated returnn part with datasets only showing returnn common part) generates this code, which to me looks good:
```python
sys.path.insert(
    0,
    "/u/hilmes/experiments/tts_new_sis/work/i6_core/tools/git/CloneGitRepositoryJob.1PthpathLjCM/output/returnn_common/..",
)
from returnn_common import nn

sys.path.insert(0, os.path.dirname(__file__))
import resource
import sys

try:
    resource.setrlimit(resource.RLIMIT_STACK, (2**29, -1))
except Exception as exc:
    print(f"resource.setrlimit {type(exc).__name__}: {exc}")
sys.setrecursionlimit(10**6)

speaker_labels_time = nn.SpatialDim("speaker_labels_time", None)
audio_features_feature = nn.FeatureDim("audio_features_feature", 80)
speaker_labels_indices = nn.FeatureDim("speaker_labels_indices", 251)
phonemes_indices = nn.FeatureDim("phonemes_indices", 43)
phonemes_time = nn.SpatialDim("phonemes_time", None)
audio_features_time = nn.SpatialDim("audio_features_time", None)
audio_features = nn.Data(
    name="audio_features",
    available_for_inference=True,
    dim_tags=[nn.batch_dim, audio_features_time, audio_features_feature],
    sparse_dim=None,
)
phonemes = nn.Data(
    name="phonemes",
    available_for_inference=True,
    dim_tags=[nn.batch_dim, phonemes_time],
    sparse_dim=phonemes_indices,
)
speaker_labels = nn.Data(
    name="speaker_labels",
    available_for_inference=True,
    dim_tags=[nn.batch_dim, speaker_labels_time],
    sparse_dim=speaker_labels_indices,
)
audio_features_args = audio_features.get_kwargs()
audio_features_args.pop("name")
phonemes_args = phonemes.get_kwargs()
phonemes_args.pop("name")
speaker_labels_args = speaker_labels.get_kwargs()
speaker_labels_args.pop("name")

extern_data = {
    "audio_features": audio_features_args,
    "phonemes": phonemes_args,
    "speaker_labels": speaker_labels_args,
}

from i6_private.users.hilmes.nar_tts.models.ctc_aligner import CTCAligner

from i6_private.users.hilmes.nar_tts.models.ctc_aligner import construct_network


network_kwargs = {
    "net_module": CTCAligner,
    "audio_data": audio_features,
    "label_data": speaker_labels,
    "phoneme_data": phonemes,
    "audio_time_dim": audio_features_time,
    "label_time_dim": speaker_labels_time,
}


def get_network(epoch, **kwargs):
    nn.reset_default_root_name_ctx()
    net = construct_network(epoch, **network_kwargs)
    return nn.get_returnn_config().get_net_dict_raw_dict(net)
```
```python
def construct_network(
  epoch: int,
  net_module: nn.Module,
  phoneme_data: nn.Data,  # phoneme labels
  duration_data: nn.Data,  # durations
  label_data: nn.Data,  # speaker labels
  audio_data: nn.Data,  # target speech
  time_dim: nn.Dim,  # phoneme time dim
  label_time_dim: nn.Dim,  # speaker_label time
  speech_time_dim: nn.Dim,  # audio features time
  duration_time_dim: nn.Dim,  # durations time
  **kwargs):
  net = net_module(**kwargs)
  out = net(text=nn.get_extern_data(phoneme_data),
            durations=nn.get_extern_data(duration_data),
            speaker_labels=nn.get_extern_data(label_data),
            target_speech=nn.get_extern_data(audio_data),
            time_dim=time_dim,
            label_time=label_time_dim,
            speech_time=speech_time_dim,
            duration_time=duration_time_dim
  )
  out.mark_as_default_output()

  return net
```

@albertz @JackTemaki any ideas what goes wrong here? Manual construction as below works, so the model itself should be fine.
```python
serializer = nn.ReturnnConfigSerializer(name_ctx_network)
base_string = serializer.get_base_extern_data_py_code_str()
network_string = serializer.get_ext_net_dict_py_code_str(net, ref_extern_data_dims_via_global_config=True,
                                                             with_imports=True)
```

**Comment by albertz** [comment]
What exactly is the exception you get? Your error message and traceback is incomplete.

**Comment by Atticus1806** [comment]
oh my bad, now it should show the correct error and traceback

**Comment by albertz** [comment]
Yes I have an idea, this might be related due to `get_network` maybe being called multiple times with different TF graphs/sessions (in such cases dim tags sometimes would reset themselves and might lose the `batch` info). In that case, it would be a RETURNN bug.

Can you copy whatever comes out of `network_string` to some Gist?

**Comment by Atticus1806** [comment]
Never worked with gist before but I think this should work: [batch.config](https://gist.github.com/Atticus1806/cc55adb827dadddb47c2733b0370fa05)

I also built a smaller testcase which fails maybe this helps:
```python
def test_returnn_batch():
  from returnn_common import nn 
  nn.reset_default_root_name_ctx()
  audio_features_feature = nn.FeatureDim("audio_features_feature", 80)
  audio_features_time = nn.SpatialDim("audio_features_time", None)
  audio_features = nn.Data(
    name="data",
    available_for_inference=True,
    dim_tags=[nn.batch_dim, audio_features_time, audio_features_feature],
    sparse_dim=None,
  )
  data = nn.get_extern_data(audio_features)
  net = nn.Linear(out_dim=audio_features_feature)
  one = net(data)
  one.mark_as_default_output()
  network = nn.get_returnn_config().get_net_dict_raw_dict(net)
  config = Config({"extern_data": {"data": {"dim_tags": (nn.batch_dim, audio_features_time, audio_features_feature), "dtype": "float32"}}})
  with make_scope():
    net = TFNetwork(config=config, train_flag=True)
    net.construct_from_dict(network)
```

**Comment by albertz** [comment]
I simplified the test a bit:
```python
def test_get_extern_data_dim_tag():
  from returnn.config import Config
  from .returnn_helpers import make_scope
  from returnn.tf.network import TFNetwork
  nn.reset_default_root_name_ctx()

  audio_features_feature = nn.FeatureDim("audio_features_feature", 8)
  audio_features_time = nn.SpatialDim("audio_features_time", None)
  audio_features = nn.Data(
    name="data",
    available_for_inference=True,
    dim_tags=[nn.batch_dim, audio_features_time, audio_features_feature],
    sparse_dim=None,
  )
  # This call here causes the dim tags to be somehow broken.
  nn.get_extern_data(audio_features)

  net_dict = {
    'output': {'class': 'linear', 'from': 'data', 'out_dim': audio_features_feature},
  }

  config = Config({
    "extern_data": {
      "data": {"dim_tags": (nn.batch_dim, audio_features_time, audio_features_feature), "dtype": "float32"}}})

  with make_scope():
    net = TFNetwork(config=config, train_flag=True)
    net.construct_from_dict(net_dict)
```

Further, I noticed that the `nn.get_extern_data` call here seem to cause the problem. Without it, the problem does not occur.

**Comment by albertz** [comment]
So https://github.com/rwth-i6/returnn/pull/1067 is merged now. So this here is fixed now?

**Comment by Atticus1806** [comment]
Apparently this was not the issue. While both tests run now (your and the small one I wrote), the gist config is not working.

**Comment by albertz** [comment]
> the gist config is not working.

It seems your [Gist config](https://gist.github.com/Atticus1806/cc55adb827dadddb47c2733b0370fa05) is also incomplete. I don't see the full config there. E.g.:
```python
label_time_dim = config.typed_dict['label_time_dim']
```
So where do I see `label_time_dim` actually defined?

What I would like to have is a complete config, which you can directly run as-is in RETURNN.

If possible, reduced as much as possible.

Or if possible, even a RETURNN test case directly, reduced as much as possible.

> What exactly does the -1 mean in the Batch description?

Nothing, it was just an arbitrary number I put there.

> I assume its not the initial BatchInfo, its changed and not updated for `dyn_size_ext`?

Yes, it's not the same batch info. That is what the error says.

One batch info is created from `extern_data` automatically. This is what you see as `BatchInfo{B}` in the log. The other batch info is created explicitly by returnn-common, which you see as `BatchInfo{B(-1)}` in the log.

I wonder how/why or where exactly we get this mixup.

**Comment by albertz** [comment]
Note, in theory, it should not be a problem to have a dim tag with a dyn size defined for multiple different batch info (e.g. different computation graphs, via multiple net inits). RETURNN should automatically select the right dim tag and dyn size. This is via `Data._adapt_batch_consistent_dim_tags`, and then `Dim._validate_in_current_graph` should drop any invalid ones. I assume some of this mechanism does not correctly work here.

Maybe it's actually valid in the current graph (see my question above). Both are then valid. The `BatchInfo{B(-1)}` is independent of the graph anyway. But still I don't exactly understand how the mixup happened then.

I think in returnn-common `_data_from_layer_dict.<locals>._get_layer_name`, maybe that `ref.data` is already not consistent?

**Comment by albertz** [comment]
Simplified test case for returnn-common:
```python
def test_returnn_config_direct_construction():
  from returnn.config import Config
  from returnn.tf.engine import Engine
  time_dim = nn.SpatialDim("time")
  in_dim = nn.FeatureDim("in", 3)
  x = nn.Data("x", dim_tags=[nn.batch_dim, time_dim, in_dim], available_for_inference=True)

  def _config_get_network(epoch: int, **_kwargs) -> dict:
    epoch  # unused  # noqa
    nn.reset_default_root_name_ctx()
    net = nn.Linear(nn.FeatureDim("out", 5))
    out = net(nn.get_extern_data(x))
    out.mark_as_default_output()
    out.mark_as_loss()
    net_dict = nn.get_returnn_config().get_net_dict_raw_dict(net)
    return net_dict

  config = Config({
    "task": "train",
    "get_network": _config_get_network,
    "extern_data": {x.name: {"dim_tags": [nn.batch_dim, time_dim, in_dim], "available_for_inference": True}},
  })
  engine = Engine(config)
  engine.init_train_from_config(config)
```
